import React from 'react';
import ChallengeCard from '../components/ChallengeCard';

export default function RouteCPage() {
  return (
    <div className="min-h-screen bg-[#F7F8FA]">

      <header className="border-b border-slate-200 bg-white">

        <div className="max-w-6xl mx-auto px-5 py-4 flex justify-between items-center">

          <div>

            <div className="font-semibold text-slate-900">
              CYBER HUNT 2026
            </div>

            <div className="text-[10px] font-mono text-violet-700 mt-1">
              PHANTOM / NODE PHM-C
            </div>

          </div>

          <div className="flex items-center gap-2 text-[10px] font-mono text-slate-400">

            <span className="w-1.5 h-1.5 rounded-full bg-violet-500" />

            LEVEL 03

          </div>

        </div>

      </header>


      <main className="min-h-[calc(100vh-73px)] flex items-center justify-center px-5 py-10">

        <ChallengeCard
          routeCode="C"
          nodeId="PHM-C"
          challengeTitle="Ghost Traffic"
          category="Network Forensics"
          difficulty="Hard"

          description={
            <>
              <div className="space-y-4">

                <div className="font-semibold text-slate-900">
                  NIT Jalandhar SOC — Network Investigation
                </div>

                <p>
                  The SOC detected unusual outbound traffic from a
                  workstation shortly before the incident was discovered.
                </p>

                <p>
                  No suspicious executable or malicious document was found
                  on the machine. Investigators therefore captured the
                  network traffic generated during the suspected compromise.
                </p>

                <p>
                  The recovered packet capture contains both legitimate
                  traffic and communication generated by the attacker.
                </p>

                <p className="font-semibold text-slate-900">
                  Investigate the traffic and recover the hidden message.
                </p>


                <div className="border border-slate-200 rounded-lg bg-slate-50 p-4">

                  <div className="text-[10px] font-mono uppercase tracking-wider text-violet-700 font-semibold">
                    Investigation Objective
                  </div>

                  <div className="mt-2 text-xs text-slate-600 leading-6">
                    Analyze the PCAP using Termux. Identify the suspicious
                    DNS traffic, extract the concealed data and decode it
                    to recover the final flag.
                  </div>

                </div>


                <div className="border border-violet-200 rounded-lg bg-violet-50/50 p-4">

                  <div className="text-[10px] font-mono uppercase tracking-wider text-violet-700 font-semibold">
                    Evidence
                  </div>

                  <a
                    href="/ghost_traffic.pcap"
                    download="ghost_traffic.pcap"
                    className="inline-flex items-center mt-2 text-xs font-mono text-violet-700 hover:text-violet-900 underline underline-offset-2"
                  >
                    Download ghost_traffic.pcap
                  </a>

                </div>


                <div className="border border-slate-200 rounded-lg bg-white p-4">

                  <div className="text-[10px] font-mono uppercase tracking-wider text-slate-500 font-semibold">
                    Environment
                  </div>

                  <div className="mt-2 text-xs text-slate-600 leading-6">

                    Termux is recommended for this investigation.
                    Network-analysis utilities may be required to inspect
                    the captured traffic.

                  </div>

                </div>

              </div>
            </>
          }

          hint="The packet capture contains a large amount of normal traffic. Focus on DNS requests and inspect the queried domains carefully. The hidden data is encoded."

          nextNode="PHM-D"
        />

      </main>

    </div>
  );
}